name = "sennheiser-dealer-portal"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "brand-detail-form"
database_id = "8e42e73c-26c8-44ea-be0f-6295bf7ba450"
